### ISSUE TITLE
about hico_detect_trainvaltest_detections.pkl

### ISSUE THREAD

**Issue by ZHUXUHAN** [SiyuanQi/gpnn#10]
can you provide the hico_detect_trainvaltest_detections.pkl

**Comment by SiyuanQi-zz** [comment]
You can download it from [here](https://drive.google.com/open?id=1gROiGvFNt6g4IgBBPHp_Ulvl4W2oLJ5z).

**Comment by karenyun** [comment]
Hi，do you know the formation of the ' hico_detect_trainvaltest_detections.pkl', I found that it is a very large list, but what does it represent?

**Comment by Chenghao-Ding** [comment]
> hico_detect_trainvaltest_detections.pkl

Hi，I have the same question with you. Do you konw how to make the hico_detect_trainvaltest_detection.pkl? It may use the trained model to deteact the trainvaltest.txt' images and save the informations. Thanks!
