### ISSUE TITLE
End-to-end with detector

### ISSUE THREAD

**Issue by gurkirt** [SiyuanQi/gpnn#12]
Dear Authors, 

Thank you very much for releasing the code (https://github.com/SiyuanQi/gpnn) of your GPNN for HOI work. I liked your work and was planning to use your code. 

While I was going through the code I noticed that deformable CNN detector code is not included. In your paper, you mentioned that one can train this pipeline into end-to-end manner. Did you train HICO and V-COCO dataset in end-to-end training or preprocessed the features computation using D-CNN detector? OR you just released the evaluation code with pre-processed features?

I will open the issue on GitHub. If you could answer there that would be great, not only but anyone who has this question.

Thanks-Gurkirt

**Comment by SiyuanQi-zz** [comment]
We preprocessed the features computation using D-CNN detector. You can make the entire framework end-to-end, which will require extra engineering efforts.
