### ISSUE TITLE
Help! Does anyone encounters the problem that "No module named vsrl_eval"?

### ISSUE THREAD

**Issue by CherryBear1314** [SiyuanQi/gpnn#15]
When running vcoco.py ,I have  the problem of "No module named vsrl_eval"? Have you ever had the same problem?And  how can I  find this function? Thanks very much ！
![000](https://user-images.githubusercontent.com/26153852/54892452-932da000-4eec-11e9-98cd-05d6db952107.jpg)

**Comment by SiyuanQi-zz** [comment]
Hi, the `vsrl_eval` module is from the v-coco dataset tools.
You can find the details [here](https://github.com/s-gupta/v-coco).

**Comment by CherryBear1314** [comment]
I got it. Thank you very much!
