### ISSUE TITLE
The Google Cloud Disk link is invalid. Please provide a new Google Cloud Disk link to the tmp folder, otherwise my graduate degree will be delayed.

### ISSUE THREAD

**Issue by 2589996558** [SiyuanQi/gpnn#32]
The Google Cloud Disk link is invalid. Please provide a new Google Cloud Disk link to the tmp folder, otherwise my graduate degree will be delayed.

**Comment by SiyuanQi** [comment]
Please try this link: https://drive.google.com/drive/folders/1vrY7dEautbrScO2kITdFR0kf9Te_GMAJ?usp=sharing

**Comment by 2589996558** [comment]
Wow, the author replied to me. Thank you, I feel really honored. I have the confidence to continue learning in the direction of video based Human Object Interaction Detection. I will immediately download the tmp folder and reproduce the model
