### ISSUE TITLE
Question about the feature size in hico.py

### ISSUE THREAD

**Issue by carrierlxk** [SiyuanQi/gpnn#5]
Nice code.  I have run the testing code of hico.py on pytorch 0.4.1 with python 3.0. The pre-extracted edge feature size is 200 and node feature size is 298. However, in the paper it said that the node feature is 7x7x80 which is not equal to 298, can you explain this issue?

**Comment by ZHUXUHAN** [comment]
hi, i also want to  know the reasons, if you understand it,can you answer it

**Comment by ZHUXUHAN** [comment]
hi, I also use pytorch 0.4.1 with python 3.5,but I can't use the model_best.pth the author uploaded,  i think it's the encoding problem ,so I start training directly not use the pre-trained model, can you provide your solutions  to the problem.
 
thanks

**Comment by carrierlxk** [comment]
Yes, you should add (encoding='bytes')  when you load the model. You can just google it

**Comment by ZHUXUHAN** [comment]
> Yes, you should add (encoding='bytes') when you load the model. You can just google it

oh,thank,i solve it

**Comment by ZHUXUHAN** [comment]
> Nice code. I have run the testing code of hico.py on pytorch 0.4.1 with python 3.0. The pre-extracted edge feature size is 200 and node feature size is 298. However, in the paper it said that the node feature is 7x7x80 which is not equal to 298, can you explain this issue?

hi, do you understand this problem?

**Comment by ZHUXUHAN** [comment]
> Nice code. I have run the testing code of hico.py on pytorch 0.4.1 with python 3.0. The pre-extracted edge feature size is 200 and node feature size is 298. However, in the paper it said that the node feature is 7x7x80 which is not equal to 298, can you explain this issue?

hi, sir,have you been following this project recently?

**Comment by SiyuanQi-zz** [comment]
The description in the paper is outdated, sorry for the misunderstanding caused. The final feature is 200+49*2. For human features we fill in the first 49, and for object features we fill in the second half. Details can be found [here](https://github.com/SiyuanQi/gpnn/blob/master/src/python/datasets/VCOCO/parse_features.py#L130-L137).

**Comment by Gaoyiminggithub** [comment]
@carrierlxk hi, I also want to know the reasons. Do you know how to get the node and edge features?
